server:
  port: 8090
  shutdown: graceful # 천천히 내려가게 하는 설정
spring:
  autoconfigure:
    exclude:
  lifecycle:
    timeout-per-shutdown-phase: 1h # 스프링부트가 종료 요청을 받은 후 기다릴 수 있는 최대한의 시간
  datasource:
    url: jdbc:mysql://3.35.17.241:3309/kkhims
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level:
    com.ll.demo03: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    name: "IMS"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
data:
  redis:
    host: 172.17.0.1
    port: 6379
    password: '${custom.secret.spring.data.redis.password}'