server:
  port: 8090
  shutdown: graceful # 천천히 내려가게 하는 설정
spring:
  autoconfigure:
    exclude:
  lifecycle:
    timeout-per-shutdown-phase: 1h # 스프링부트가 종료 요청을 받은 후 기다릴 수 있는 최대한의 시간
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/ims
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true  # 기존 스키마가 있을 때 히스토리 테이블 초기화
    locations: classpath:db/migration
    validate-on-migrate: true  # 마이그레이션 검증
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${custom.mail.username}"
    password: "${custom.mail.password}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?
  data:
    redis:
      host: 172.17.0.1
      port: 6379
      password: 1234
logging:
  level:
    com.ll.demo03: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    name: "IMS"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"